# Generated by Django 4.2.1 on 2023-05-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_id_f21274_idx',
            old_fields=('id', 'slug'),
        ),
    ]
