# Generated by Django 4.2.1 on 2023-09-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_article_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.SlugField(default='qwerty', max_length=200),
            preserve_default=False,
        ),
    ]
