# Generated by Django 4.2.1 on 2023-09-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_companyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate',
            field=models.ImageField(upload_to='certificates'),
        ),
    ]
